name: yuyutsu_ereader
description: A cross-platform e-reader application built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # E-reader packages
  epub_view: ^3.0.0
  syncfusion_flutter_pdf: ^24.2.7

  # State management
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^12.1.3

  # Storage & file handling
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path: ^1.8.3
  file_picker: ^6.1.1
  permission_handler: ^11.2.0
  
  # Cloud storage
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  http: ^1.2.0
  
  # URL handling
  url_launcher: ^6.2.4

  # UI & responsive design
  flutter_screenutil: ^5.9.0

  # Utils
  equatable: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  drift_dev: ^2.14.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # Add assets folder for sample books
  assets:
    - assets/books/
    - assets/images/

  # Add custom fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf