---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    # branches-ignore: [main]
    # Remove the line above to run when pushing to main
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*(website/.*.md\.github|\.vscode|CODE_OF_CONDUCT.md|README.md|documentation|app/build|app/.*\.g\.dart|app/.*\.freezed\.dart).*
          JAVASCRIPT_DEFAULT_STYLE: prettier
          LINTER_RULES_PATH: "."
          EDITORCONFIG_FILE_NAME: .editorconfig
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false

  flutter-analyze:
    name: Flutter Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: app
        run: flutter pub get

      - name: Generate code
        working-directory: app
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze Flutter code
        working-directory: app
        run: flutter analyze
